medium/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'
  root 'blogs#index'
  resources :blogs,except: [:index] do
    collection do
      get 'my',to:'blogs#my_blogs'
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

medium/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

medium/app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :author,class_name: :User
end

medium/app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

medium/app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

medium/app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

medium/app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

medium/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

medium/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!,except:[:index]
  before_action :set_blog,only:[:edit,:update,:destroy]
  def index
    @blogs = Blog.order(:created_at).page(params[:page]).per(10) if user_signed_in?
    @blogs = Blog.order(:created_at).first(10) unless user_signed_in?
  end

  def my_blogs
    @blog = Blog.new
    @blogs = Blog.order(:created_at,:asc).where(author:current_user).page(params[:page]).per(10)
  end

  def show
  end

  def new
  end

  def create
    @blog = Blog.new
    @blog.title = params[:blog][:title]
    @blog.description = params[:blog][:description]
    @blog.author = current_user
    if @blog.save
      redirect_to my_blogs_path
    else
      render text:"Failed To Save"
    end
  end

  def update
    @blog.title = params[:blog][:title]
    @blog.description = params[:blog][:description]
    if @blog.save
      redirect_to my_blogs_path
    else
      render text:"Failed To Edit"
    end
  end

  def edit 
    if @blog.author != current_user
      redirect_to root_path
    end
  end

  def delete
  end

  def destroy
    @blog.destroy
    redirect_to my_blogs_path
  end

  private

  def set_blog
    @blog = Blog.find params[:id]
  end
end

medium/app/helpers/application_helper.rb
module ApplicationHelper
end

medium/app/helpers/blogs_helper.rb
module BlogsHelper
end

medium/app/views/blogs/_form.html.erb
<%=form_for data[:blog],url:data[:url],method: (data[:method].nil? ? :post : data[:method]) do |f|%>
	<div class="form-group">
		<%= f.label :title%>
		<%= f.text_field :title,class:"form-control"%>
	</div>
	<div class="form-group">
		<%= f.label :description%>
		<%= f.cktext_area :description,class:"form-control"%>
	</div>
	<div class="form-group">
		<%= f.submit "Submit",class:"btn btn-outline-success"%>
	</div>
<%end%>

medium/app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

medium/app/views/blogs/delete.html.erb
<h1>Blogs#delete</h1>
<p>Find me in app/views/blogs/delete.html.erb</p>

medium/app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

medium/app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>
<%=render 'form',data:{url:blog_path(@blog.id),blog:@blog,method: :patch}%>

medium/app/views/blogs/index.html.erb
<center><h1>Listing Blogs</h1></center>
<%@blogs.each do |blog|%>
<div class="card">
	<div class="card-header">
		<%="<h1>#{blog.title}</h1> <small> by #{blog.author.email}</small>".html_safe%>
	</div>
	<div class="card-body">
		<%=blog.description&.html_safe%>
	</div>
	<div class="card-footer">
		<%="#{time_ago_in_words(blog.created_at)} ago"%>
	</div>
</div>
<br><br><br>
<%end%>
<%if user_signed_in?%>
<%=paginate @blogs %>
<%else%>
<h1>Please login to view more.</h1>
<%end%>

medium/app/views/blogs/my_blogs.html.erb
<h1>New Blog</h1>
<%=render 'form',data:{url:blogs_path,blog:@blog}%>

<hr>
<h1>My Blogs</h1>
<%@blogs.each do |blog|%>
<div class="card">
	<div class="card-header">
		<%="<h1>#{blog.title}</h1> <small> by #{blog.author.email}</small>".html_safe%>
		<%= link_to 'Edit',edit_blog_path(id:blog.id)%>
		<%= link_to 'Delete',blog_path(id:blog.id),method: :delete %>
	</div>
	<div class="card-body">
		<%=blog.description&.html_safe%>
	</div>
	<div class="card-footer">
		<%="#{time_ago_in_words(blog.created_at)} ago"%>
	</div>
</div>
<br><br><br>
<%end%>
<%=paginate @blogs %>

medium/app/views/blogs/new.html.erb
<h1>Blogs#new</h1>
<p>Find me in app/views/blogs/new.html.erb</p>

medium/app/views/blogs/show.html.erb
<h1>Blogs#show</h1>
<p>Find me in app/views/blogs/show.html.erb</p>

medium/app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>

medium/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medium</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%=render 'shared/nav'%>
  <!-- Begin page content -->
  <main role="main" class="flex-shrink-0">
    <div class="container">
      <%= yield %>
    </div>
  </main>

  <%=render 'shared/footer'%>

</body>
</html>

medium/app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
	<div class="container">
		<span class="text-muted">Place sticky footer content here.</span>
	</div>
</footer>

medium/app/views/shared/_nav.html.erb
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Medium</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home",root_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "My Blogs",my_blogs_path,class:"nav-link"%>
        </li>
      </ul>
        <%= link_to "Logout",destroy_user_session_path,method: :delete,class:"btn btn-danger my-2 my-sm-0" if user_signed_in? %>
        <%= link_to "Login",new_user_session_path,class:"btn btn-success my-2 my-sm-0" unless user_signed_in?%>
    </div>
  </nav>
</header>